//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPPrintingApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SessionKey {
            get {
                return ((string)(this["SessionKey"]));
            }
            set {
                this["SessionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string INVOICE_PRINTER {
            get {
                return ((string)(this["INVOICE_PRINTER"]));
            }
            set {
                this["INVOICE_PRINTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string INVOICE_PRINTER_DRAWER {
            get {
                return ((string)(this["INVOICE_PRINTER_DRAWER"]));
            }
            set {
                this["INVOICE_PRINTER_DRAWER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int INVOICE_PRINTER_PAPER_WIDTH {
            get {
                return ((int)(this["INVOICE_PRINTER_PAPER_WIDTH"]));
            }
            set {
                this["INVOICE_PRINTER_PAPER_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WAREHOUSE {
            get {
                return ((int)(this["WAREHOUSE"]));
            }
            set {
                this["WAREHOUSE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.northerner.com/index.php/api/V2_soap/index/")]
        public string ERPPrintingApplication_MagentoSoapAPI_MagentoService {
            get {
                return ((string)(this["ERPPrintingApplication_MagentoSoapAPI_MagentoService"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LABEL_PRINTER {
            get {
                return ((string)(this["LABEL_PRINTER"]));
            }
            set {
                this["LABEL_PRINTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LABEL_PRINTER_DRAWER {
            get {
                return ((string)(this["LABEL_PRINTER_DRAWER"]));
            }
            set {
                this["LABEL_PRINTER_DRAWER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LABEL_PRINTER_PAPER_WIDTH {
            get {
                return ((int)(this["LABEL_PRINTER_PAPER_WIDTH"]));
            }
            set {
                this["LABEL_PRINTER_PAPER_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LABEL_PRINTER_PAPER_HEIGHT {
            get {
                return ((int)(this["LABEL_PRINTER_PAPER_HEIGHT"]));
            }
            set {
                this["LABEL_PRINTER_PAPER_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RETURN_ADDRESS1 {
            get {
                return ((string)(this["RETURN_ADDRESS1"]));
            }
            set {
                this["RETURN_ADDRESS1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RETURN_ADDRESS2 {
            get {
                return ((string)(this["RETURN_ADDRESS2"]));
            }
            set {
                this["RETURN_ADDRESS2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int INVOICE_PRINTER_PAPER_HEIGHT {
            get {
                return ((int)(this["INVOICE_PRINTER_PAPER_HEIGHT"]));
            }
            set {
                this["INVOICE_PRINTER_PAPER_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int INVOICE_PRINTER_MARGIN_TOP {
            get {
                return ((int)(this["INVOICE_PRINTER_MARGIN_TOP"]));
            }
            set {
                this["INVOICE_PRINTER_MARGIN_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int INVOICE_PRINTER_MARGIN_LEFT {
            get {
                return ((int)(this["INVOICE_PRINTER_MARGIN_LEFT"]));
            }
            set {
                this["INVOICE_PRINTER_MARGIN_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UPS_IMPORT_PATH {
            get {
                return ((string)(this["UPS_IMPORT_PATH"]));
            }
            set {
                this["UPS_IMPORT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UPS_WEIGHT_TYPE {
            get {
                return ((int)(this["UPS_WEIGHT_TYPE"]));
            }
            set {
                this["UPS_WEIGHT_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UPGRADE_TO_UPS {
            get {
                return ((bool)(this["UPGRADE_TO_UPS"]));
            }
            set {
                this["UPGRADE_TO_UPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string UPS_UPGRADE_WEIGHT {
            get {
                return ((string)(this["UPS_UPGRADE_WEIGHT"]));
            }
            set {
                this["UPS_UPGRADE_WEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REQ_ADULT {
            get {
                return ((bool)(this["REQ_ADULT"]));
            }
            set {
                this["REQ_ADULT"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\BarcodeData.mdf;Inte" +
            "grated Security=True")]
        public string BarcodeDataConnectionString {
            get {
                return ((string)(this["BarcodeDataConnectionString"]));
            }
        }
    }
}
